package(default_applicable_licenses = ["//third_party/intellij/bazel:license"])

java_library(
    name = "nodeps",
    srcs = ["TestClassNoDeps.java"],
    visibility = ["//querysync/javatests/com/google/idea/blaze/qsync/testdata:__subpackages__"],
)
