load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "nodeps",
    srcs = ["TestClassNoDeps.java"],
    visibility = ["//querysync/javatests/com/google/idea/blaze/qsync/testdata:__subpackages__"],
)
