package(
    default_visibility = [
        "//querysync:__subpackages__",
        "//querysync/java/com/google/idea/blaze/qsync:__pkg__",
    ],
)

java_library(
    name = "vcs",
    srcs = glob(["*.java"]),
    deps = [
        "@com_google_guava_guava//jar",
    ],
)
