licenses(["notice"])

java_library(
    name = "common",
    srcs = glob(["*.java"]),
    visibility = ["//shared:__subpackages__"],
    deps = [
        "//third_party/auto_value",
        "@com_google_guava_guava//jar",
        "@com_google_errorprone_error_prone_annotations//jar",
        "@com_google_code_findbugs_jsr305//jar",
    ],
)
