licenses(["notice"])

java_library(
    name = "common",
    srcs = glob(["*.java"]),
    visibility = ["//shared:__subpackages__"],
    deps = [
        "@error_prone_annotations//jar",
        "@jsr305_annotations//jar",
    ],
)
