---

policy:
  - template: [bug_report.yml, feature_request.yml]
    section:
      - id: [subteam]
        label:
          - name: 'product: IntelliJ'
            keys: ['Intellij']
          - name: 'product: GoLand'
            keys: ['GoLand']
          - name: 'product: CLion'
            keys: ['CLion']
          - name: 'product: PyCharm'
            keys: ['PyCharm']
          - name: 'product: Android Studio'
            keys: ['Android Studio']
