load("//build_defs:intellij_integration_test.bzl", "intellij_integration_test")

intellij_integration_test(
    test = "SkylarkReplTest.kt",
    deps = [
        "//common/util:runjar",
        "//skylark/src/com/google/idea/blaze/skylark/repl",
    ],
)
