load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//base:__subpackages__"])

java_library(
    name = "test",
    srcs = glob(["*.java"]),
)

filegroup(
    name = "test_srcs",
    srcs = glob(["*.java"]),
)
