package(default_applicable_licenses = ["//third_party/intellij/bazel:license"])

java_library(
    name = "externaldep",
    srcs = ["TestClassExternalDep.java"],
    visibility = ["//querysync/javatests/com/google/idea/blaze/qsync/testdata:__subpackages__"],
    deps = ["@com_google_guava_guava//jar"],
)
