java_library(
    name = "externaldep",
    srcs = ["TestClassExternalDep.java"],
    visibility = ["//querysync/javatests/com/google/idea/blaze/qsync/testdata:__subpackages__"],
    deps = ["//querysync/javatests/com/google/idea/blaze/qsync/testdata/nodeps"],
)
