java_library(
    name = "inner",
    srcs = ["TestClassAnotherExternalDep.java"],
    visibility = ["//querysync/javatests/com/google/idea/blaze/qsync/testdata:__subpackages__"],
    deps = ["@com_google_code_gson_gson//jar"],
)
