load("//build_defs:intellij_unit_test.bzl", "intellij_unit_test")

intellij_unit_test(
    test = "ProcSelfCwdEnvironmentProcessorTest.kt",
    deps = [
        "//base",
        "//base:unit_test_utils",
        "//cpp",
        "@com_google_guava_guava//jar",
    ],
)
