load("//build_defs:intellij_integration_test.bzl", "intellij_integration_test")

intellij_integration_test(
    test = "ExeclogParserTest.kt",
    deps = [
        "//base/src/com/google/idea/blaze/base/execlog",
        "//common/util:runjar",
    ],
)
