load("@rules_java//java:defs.bzl", "java_library")

licenses(["notice"])

java_library(
    name = "vcs",
    srcs = glob(["*.java"]),
    visibility = ["//shared:__subpackages__"],
    deps = [
        "@com_google_guava_guava//jar",
    ],
)
