load("//build_defs:intellij_unit_test.bzl", "intellij_unit_test")

intellij_unit_test(
    test = "DebugInfoCheckTest.kt",
    test_package = "com.google.idea.blaze.clwb.run",
    deps = [
        "//clwb:clwb_lib",
        "//base",
    ],
)
