/*
 * Copyright 2019 The Bazel Authors. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.idea.blaze.base.query;

import com.google.common.collect.ImmutableList;
import com.google.idea.blaze.base.bazel.BazelExitCodeException.ThrowOption;
import com.google.idea.blaze.base.buildview.BazelExecService;
import com.google.idea.blaze.base.command.BlazeCommand;
import com.google.idea.blaze.base.command.BlazeCommandName;
import com.google.idea.blaze.base.model.primitives.Label;
import com.google.idea.blaze.base.model.primitives.TargetExpression;
import com.google.idea.blaze.base.scope.Scope;
import com.google.idea.blaze.base.scope.scopes.IdeaLogScope;
import com.google.idea.blaze.exception.BuildException;
import com.google.idea.common.experiments.BoolExperiment;
import com.intellij.execution.ExecutionException;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.openapi.project.Project;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import javax.annotation.Nullable;

/** Uses 'blaze query' to find all targets in a single package generated by macros. */
public class BlazeQueryMacroTargetProvider implements MacroTargetProvider {

  private final BoolExperiment enabled =
      new BoolExperiment("blaze.query.macro.target.provider.enabled", true);

  private static final Logger logger = Logger.getInstance(BlazeQueryMacroTargetProvider.class);

  @Nullable
  @Override
  public ImmutableList<GeneratedTarget> doFindTargets(Project project, Label buildPackage) {
    if (!enabled.getValue()) {
      return null;
    }
    return runQuery(project, buildPackage);
  }

  @Nullable
  private static ImmutableList<GeneratedTarget> runQuery(Project project, Label label) {
    String outputBase = BlazeQueryOutputBaseProvider.getInstance(project).getOutputBaseFlag();
    if (outputBase == null) {
      // since this is run automatically in the background, don't run without a custom output base,
      // otherwise we'll be monopolizing the primary blaze server
      return null;
    }
    String query =
        String.format(
            "attr('generator_function', '^.+$', %s)",
            TargetExpression.allFromPackageNonRecursive(label.blazePackage()));

    final var command = BlazeCommand.builder(BlazeCommandName.QUERY)
        .addBlazeFlags("--output=proto")
        .addBlazeFlags(query)
        .addBlazeStartupFlags(ImmutableList.of(outputBase));

    return Scope.root(context -> {
      context.push(new IdeaLogScope());

      try (final var result = BazelExecService.of(project).exec(context, command)) {
        result.throwOnFailure(ThrowOption.ALLOW_PARTIAL_SUCCESS);
        return BlazeQueryProtoParser.parseProtoOutput(result.getStdout());
      } catch (IOException e) {
        logger.warn("Couldn't parse blaze query proto output", e);
        return null;
      } catch (ExecutionException | BuildException e) {
        logger.warn("Failed to run blaze query", e);
        return null;
      }
    });
  }
}
