load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "transitiveinternaldep",
    srcs = ["TestClassTransiviteInternalDep.java"],
    deps = ["//querysync/javatests/com/google/idea/blaze/qsync/testdata/internaldep"],
)
