load("@rules_java//java:defs.bzl", "java_binary")
load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary")

java_binary(
    name = "main_java",
    main_class = "simple.Main",
    srcs = ["src/simple/Main.java"],
    deps = [],
)

kt_jvm_binary(
    name = "main_kotlin",
    main_class = "simple.Main",
    srcs = ["src/simple/Main.kt"],
    deps = [],
)
