load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_googletest",
    integrity = "sha256-8XnsIX+bOz88bosC0+ftqZe0nkzibWsjXJBTvsnAv58=",
    strip_prefix = "googletest-1.15.2",
    urls = ["https://github.com/google/googletest/archive/refs/tags/v1.15.2.zip"],
)
