name: Bug Report
description: File a bug report
labels: ["type: bug", "awaiting-maintainer"]
assignees:
  - satyanandak
  - sgowroji
  - iancha1992
body:
  - type: markdown
    attributes:
      value: >
        **Attention:** if this is a _question_ about how to build / test / query / deploy using
        Bazel intellij, or a _discussion starter_, send it to intellij-bazel-plugin@googlegroups.com or discuss on
        [Bazel intellij Slack](https://bazelbuild.slack.com/archives/C025SBYFC4E) channel instead!
  - type: textarea
    id: bug
    attributes:
      label: >
        Description of the bug:
  - type: dropdown
    id: subteam
    attributes:
      label: Which category does this issue belong to?
      description: Help us triage this issue faster and more accurately to the relevant team(s).
      multiple: true
      options:
        - Intellij
        - GoLand
        - CLion
        - PyCharm
        - Android Studio
  - type: textarea
    id: repro
    attributes:
      label: >
        What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if
        possible.
  - type: input
    id: product
    attributes:
      label: >
        Which Intellij IDE are you using? Please provide the specific version.
  - type: input
    id: tools
    attributes:
      label: >
        What programming languages and tools are you using? Please provide specific versions.
  - type: input
    id: plugin
    attributes:
      label: >
        What Bazel plugin version are you using?
  - type: textarea
    id: relevant-info
    attributes:
      label: Have you found anything relevant by searching the web?
      description: >
        Places to look:

         * GitHub issues: https://github.com/bazelbuild/intellij/issues
         * Email threads on https://groups.google.com/forum/#!forum/intellij-bazel-plugin
  - type: textarea
    id: extras
    attributes:
      label: Any other information, logs, or outputs that you want to share?
