name: Feature Request
description: Suggest a new feature
body:
  - type: markdown
    attributes:
      value: >
        **Attention:** if this is a _question_ about how to build / test / query / deploy using
        Bazel intellij, or a _discussion starter_, send it to bazel-discuss@googlegroups.com or discuss on
        [Bazel Slack](https://slack.bazel.build/) #intellij channel instead!
  - type: textarea
    id: desc
    attributes:
      label: >
        Description of the feature request:
  - type: textarea
    id: problem
    attributes:
      label: >
        What underlying problem are you trying to solve with this feature?
  - type: input
    id: os
    attributes:
      label: >
        Which operating system, Intellij IDE, Programming language and their versions?
  - type: textarea
    id: relevant-info
    attributes:
      label: Have you found anything relevant by searching the web?
      description: >
        Places to look:

         * GitHub issues: https://github.com/bazelbuild/intellij/issues
         * Email threads on https://groups.google.com/forum/#!forum/bazel-discuss
  - type: textarea
    id: extras
    attributes:
      label: Any other information, logs, or outputs that you want to share?