name: Feature Request
description: Suggest a new feature
labels: ["type: feature request", "awaiting-maintainer"]
assignees:
  - satyanandak
  - sgowroji
  - iancha1992
body:
  - type: markdown
    attributes:
      value: >
        **Attention:** if this is a _question_ about how to build / test / query / deploy using
        Bazel intellij, or a _discussion starter_, send it to intellij-bazel-plugin@googlegroups.com or discuss on
        [Bazel intellij Slack](https://bazelbuild.slack.com/archives/C025SBYFC4E) channel instead!
  - type: textarea
    id: feature
    attributes:
      label: >
        Description of the feature request:
  - type: dropdown
    id: subteam
    attributes:
      label: Which category does this issue belong to?
      description: Help us triage this issue faster and more accurately to the relevant team(s).
      multiple: true
      options:
        - Intellij
        - GoLand
        - CLion
        - PyCharm
        - Android Studio
  - type: textarea
    id: problem
    attributes:
      label: >
        What underlying problem are you trying to solve with this feature?
  - type: input
    id: os
    attributes:
      label: >
        What operating system, Intellij IDE and programming languages are you using? Please provide specific versions.
  - type: textarea
    id: relevant-info
    attributes:
      label: Have you found anything relevant by searching the web?
      description: >
        Places to look:

         * GitHub issues: https://github.com/bazelbuild/intellij/issues
         * Email threads on https://groups.google.com/forum/#!forum/intellij-bazel-plugin
  - type: textarea
    id: extras
    attributes:
      label: Any other information, logs, or outputs that you want to share?
