java_library(
    name = "noide",
    srcs = ["TestClass.java"],
    tags = ["no-ide"],
    visibility = ["//querysync/javatests/com/google/idea/blaze/qsync/testdata:__subpackages__"],
)

java_library(
    name = "yeside",
    srcs = ["TestClass.java"],
    visibility = ["//querysync/javatests/com/google/idea/blaze/qsync/testdata:__subpackages__"],
)
