load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//base:__subpackages__"])

java_library(
    name = "test2",
    srcs = ["Test.java"],
)

filegroup(
    name = "test2_srcs",
    srcs = ["Test.java"],
)
