package(default_applicable_licenses = ["//third_party/intellij/bazel:license"])

java_library(
    name = "transitivedep",
    srcs = ["TestClassTransitiveDep.java"],
    deps = ["//querysync/javatests/com/google/idea/blaze/qsync/testdata/externaldep"],
)
