load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "transitivedep",
    srcs = ["TestClassTransitiveDep.java"],
    deps = ["//querysync/javatests/com/google/idea/blaze/qsync/testdata/externaldep"],
)
