load("@rules_java//java:defs.bzl", "java_library")

licenses(["notice"])

java_library(
    name = "exception",
    srcs = glob(["*.java"]),
    visibility = [
        "//aswb:__subpackages__",
        "//base:__subpackages__",
        "//shared:__subpackages__",
    ],
)
