load("//testing/bazel:project_archive.bzl", "project_archive")

package(default_visibility = ["//visibility:public"])

project_archive(
    name = "clang_cl",
    srcs = glob(["clang_cl/**"]),
    strip_prefix = "clang_cl",
)

project_archive(
    name = "execution",
    srcs = glob(["execution/**"]),
    strip_prefix = "execution",
)

project_archive(
    name = "external_includes",
    srcs = glob(["external_includes/**"]),
    strip_prefix = "external_includes",
)

project_archive(
    name = "llvm_toolchain",
    srcs = glob(["llvm_toolchain/**"]),
    strip_prefix = "llvm_toolchain",
)

project_archive(
    name = "protobuf",
    srcs = glob(["protobuf/**"]),
    strip_prefix = "protobuf",
)

project_archive(
    name = "simple",
    srcs = glob(["simple/**"]),
    strip_prefix = "simple",
)

project_archive(
    name = "target_compatible",
    srcs = glob(["target_compatible/**"]),
    strip_prefix = "target_compatible",
)

project_archive(
    name = "transition",
    srcs = glob(["transition/**"]),
    strip_prefix = "transition",
)

project_archive(
    name = "virtual_includes",
    srcs = glob(["virtual_includes/**"]),
    strip_prefix = "virtual_includes",
)
