load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "fixture",
    testonly = 1,
    visibility = ["//visibility:public"],
    exports = ["//testing/src/com/google/idea/testing/bazel:fixture_lib"],
)
