# Description:
#
# Scripts for building IntelliJ plugins

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

py_binary(
    name = "merge_xml",
    srcs = ["merge_xml.py"],
)

py_binary(
    name = "stamp_plugin_xml",
    srcs = ["stamp_plugin_xml.py"],
)

py_binary(
    name = "product_build_txt",
    srcs = ["product_build_txt.py"],
)

py_binary(
    name = "api_version_txt",
    srcs = ["api_version_txt.py"],
)
