# Description:
#
# Scripts for building IntelliJ plugins

package(default_visibility = ["//visibility:public"])

py_binary(
    name = "merge_xml",
    srcs = ["merge_xml.py"],
)

py_binary(
    name = "stamp_plugin_xml",
    srcs = ["stamp_plugin_xml.py"],
)
