package com.google.idea.sdkcompat.querysync;

import com.intellij.codeInsight.daemon.EssentialHighlightingRestarterDisablement;

public interface EssentialHighlightingRestarterDisablementAdapter extends EssentialHighlightingRestarterDisablement {
}
