cc_library(
    name = "cc_externaldep",
    srcs = ["TestClass.cc"],
    hdrs = ["TestClass.h"],
    visibility = ["//querysync/javatests/com/google/idea/blaze/qsync/testdata:__subpackages__"],
    deps = ["//third_party/absl/strings"],
)
