java_library(
    name = "adpaters",
    testonly = 1,
    srcs = glob(["src/**"]),
    visibility = ["//:__subpackages__"],
    deps = [
        "//intellij_platform_sdk:plugin_api_for_tests",
        "@com_google_guava_guava//jar",
    ],
)
