load("//tools/build_defs/android:rules.bzl", "android_library")

package(default_applicable_licenses = ["//third_party/intellij/bazel:license"])

android_library(
    name = "android",
    srcs = ["TestAndroidClass.java"],
)
