load("//build_defs:build_defs.bzl", "intellij_plugin_library")

intellij_plugin_library(
    name = "plugin_library",
    visibility = ["//visibility:public"],
    deps = [
        "//skylark/src/com/google/idea/blaze/skylark/debugger",
    ],
)
